# Generated by src/bin/export-dns.rs. Review before applying.

resource "cloudflare_dns_record" "txt_github_pages_challenge_jackin_project_jackin_tailrocks_com_9a215640" {
  zone_id = local.zone_id
  name    = "_github-pages-challenge-jackin-project.jackin.tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"14a077c0d30b1e516a7a8c60df4db4\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_github_pages_challenge_tailrocks_apt_tailrocks_com_d516ab53" {
  zone_id = local.zone_id
  name    = "_github-pages-challenge-tailrocks.apt.tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"5e4e228922e965aaaddad1889876cf\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_github_pages_challenge_tailrocks_holla_apt_tailrocks_com_c2096a47" {
  zone_id = local.zone_id
  name    = "_github-pages-challenge-tailrocks.holla-apt.tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"bd1f126d73802bc5f6702a468c6a2b\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_github_pages_challenge_tailrocks_tailrocks_com_cbf39016" {
  zone_id = local.zone_id
  name    = "_github-pages-challenge-tailrocks.tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"3634ca6138\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_github_pages_challenge_tailrocks_velnor_apt_tailrocks_com_9fa43d72" {
  zone_id = local.zone_id
  name    = "_github-pages-challenge-tailrocks.velnor-apt.tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"dd46042c34ab34613ae28082455eac\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_cf2024_1_domainkey_tailrocks_com_37af4b7b" {
  zone_id = local.zone_id
  name    = "cf2024-1._domainkey.tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiweykoi+o48IOGuP7GR3X0MOExCUDY/BCRHoWBnh3rChl7WhdyCxW3jgq1daEjPPqoi7sJvdg5hEQVsgVRQP4DcnQDVjGMbASQtrY4WmB1VebF+RPJB2ECPsEDTpeiI5ZyUAwJaVX7r6bznU67g7LvFq35yIo4sdlmtZGV+i0H4cpYH9+3JJ78k\" \"m4KXwaf9xUJCWF6nxeD+qG6Fyruw1Qlbds2r85U9dkNDVAS3gioCvELryh1TxKGiVTkg4wqHTyHfWsp7KD3WQHYJn0RyfJJu6YEmL77zonn7p2SRMvTMP3ZEXibnC9gz3nnhR6wcYL8Q7zXypKTMD58bTixDSJwIDAQAB\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_holla_apt_tailrocks_com_890d43a1" {
  zone_id = local.zone_id
  name    = "holla-apt.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "tailrocks.github.io"
  proxied = false
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_jackin_tailrocks_com_679dcbf4" {
  zone_id = local.zone_id
  name    = "jackin.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "jackin-project.github.io"
  proxied = false
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_skills_tailrocks_com_226d9c84" {
  zone_id = local.zone_id
  name    = "skills.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "tailrocks.github.io"
  proxied = false
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "a_tailrocks_com_e17d48c3" {
  zone_id = local.zone_id
  name    = "tailrocks.com"
  type    = "A"
  ttl     = 1
  content = "192.64.119.244"
  proxied = true

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "mx_tailrocks_com_30b4c7d8" {
  zone_id  = local.zone_id
  name     = "tailrocks.com"
  type     = "MX"
  ttl      = 1
  content  = "route1.mx.cloudflare.net"
  proxied  = false
  priority = 82

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "mx_tailrocks_com_8761bb49" {
  zone_id  = local.zone_id
  name     = "tailrocks.com"
  type     = "MX"
  ttl      = 1
  content  = "route2.mx.cloudflare.net"
  proxied  = false
  priority = 52

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "mx_tailrocks_com_65bc2227" {
  zone_id  = local.zone_id
  name     = "tailrocks.com"
  type     = "MX"
  ttl      = 1
  content  = "route3.mx.cloudflare.net"
  proxied  = false
  priority = 68

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_tailrocks_com_3f206277" {
  zone_id = local.zone_id
  name    = "tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "\"v=spf1 include:_spf.mx.cloudflare.net ~all\""
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_tailrocks_com_e4c2bd8a" {
  zone_id = local.zone_id
  name    = "tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "OSSRH-80634"
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "txt_tailrocks_com_a66b58bb" {
  zone_id = local.zone_id
  name    = "tailrocks.com"
  type    = "TXT"
  ttl     = 1
  content = "gradle-verification=RWDLIORN6DY6VFPAXMERBDGVS2J2M"
  proxied = false

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_termrock_tailrocks_com_59585c3a" {
  zone_id = local.zone_id
  name    = "termrock.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "tailrocks.github.io"
  proxied = false
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_velnor_apt_tailrocks_com_3290a077" {
  zone_id = local.zone_id
  name    = "velnor-apt.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "tailrocks.github.io"
  proxied = false
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_velnor_tailrocks_com_403283ad" {
  zone_id = local.zone_id
  name    = "velnor.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "tailrocks.github.io"
  proxied = false
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "cloudflare_dns_record" "cname_www_tailrocks_com_253c5245" {
  zone_id = local.zone_id
  name    = "www.tailrocks.com"
  type    = "CNAME"
  ttl     = 1
  content = "parkingpage.namecheap.com"
  proxied = true
  settings = {
    "flatten_cname" : false
  }

  lifecycle {
    prevent_destroy = true
  }
}
