# Generated by src/bin/export-dns.rs. Keep until every record has been imported into local state.

import {
  to = cloudflare_dns_record.txt_github_pages_challenge_jackin_project_jackin_tailrocks_com_9a215640
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/9a2156401b3660576cc55334b2c1eea1"
}

import {
  to = cloudflare_dns_record.txt_github_pages_challenge_tailrocks_apt_tailrocks_com_d516ab53
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/d516ab53ae6b2a081abfe51e1b929098"
}

import {
  to = cloudflare_dns_record.txt_github_pages_challenge_tailrocks_holla_apt_tailrocks_com_c2096a47
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/c2096a47e6dbae77a63f6e5d5cde4e19"
}

import {
  to = cloudflare_dns_record.txt_github_pages_challenge_tailrocks_tailrocks_com_cbf39016
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/cbf39016bcef7fadbc3b228e34d1493e"
}

import {
  to = cloudflare_dns_record.txt_github_pages_challenge_tailrocks_velnor_apt_tailrocks_com_9fa43d72
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/9fa43d72f16e4dc498b3b18cbea4fe3c"
}

import {
  to = cloudflare_dns_record.txt_cf2024_1_domainkey_tailrocks_com_37af4b7b
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/37af4b7ba4ac65164d3eef9c72fb06e8"
}

import {
  to = cloudflare_dns_record.cname_holla_apt_tailrocks_com_890d43a1
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/890d43a1b55a38768ac484251857ccb7"
}

import {
  to = cloudflare_dns_record.cname_jackin_tailrocks_com_679dcbf4
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/679dcbf469d0f96fe72ad67e9900c08d"
}

import {
  to = cloudflare_dns_record.cname_skills_tailrocks_com_226d9c84
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/226d9c84f970e1e02b398b6219d2f05d"
}

import {
  to = cloudflare_dns_record.a_tailrocks_com_e17d48c3
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/e17d48c3a4001e377be9261458afd74d"
}

import {
  to = cloudflare_dns_record.mx_tailrocks_com_30b4c7d8
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/30b4c7d803e84f957dba17bf2b9879b4"
}

import {
  to = cloudflare_dns_record.mx_tailrocks_com_8761bb49
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/8761bb49e202c2453736e2f2381ca408"
}

import {
  to = cloudflare_dns_record.mx_tailrocks_com_65bc2227
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/65bc222744bf99ac2e2f79bcaf5a5329"
}

import {
  to = cloudflare_dns_record.txt_tailrocks_com_3f206277
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/3f2062774fdf2e6c141c4ea7884e405c"
}

import {
  to = cloudflare_dns_record.txt_tailrocks_com_e4c2bd8a
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/e4c2bd8af585c7f8f8ed934fe21f0a66"
}

import {
  to = cloudflare_dns_record.txt_tailrocks_com_a66b58bb
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/a66b58bb9d733f0a3b05b31b84f93b88"
}

import {
  to = cloudflare_dns_record.cname_termrock_tailrocks_com_59585c3a
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/59585c3a3d98a7eac520623b36bfef45"
}

import {
  to = cloudflare_dns_record.cname_velnor_apt_tailrocks_com_3290a077
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/3290a077acb86394b37e65a3a6d6e804"
}

import {
  to = cloudflare_dns_record.cname_velnor_tailrocks_com_403283ad
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/403283ad0b28dff5bd47c73a106da202"
}

import {
  to = cloudflare_dns_record.cname_www_tailrocks_com_253c5245
  id = "d959581ac83ee5b00ae4b74fa0eb3f6b/253c524538a5d36ccb1185d5e16af617"
}
